In [3]:
import numpy as np
from cs771 import genSyntheticData as gsd
from cs771 import plotData as pd
from matplotlib import pyplot as plt
import time as tm
import numpy as np
import random
import pandas

Z = np.loadtxt( "data" )

y = Z[:,0]
X = Z[:,1:]


# Quite standard for strongly convex but non-smooth objectives like CSVM
def getStepLength( grad, t ,power):
    return eta/pow(t,power)

#function that returns the sum of hingelosses for all the points __ useful for calculation of gradient 
def hingeloss(theta):
    w = theta[0:-1]
    b = theta[-1]
    hinge = np.maximum(1-np.multiply((X.dot(w) + b), y), 0)
    return np.sum(hinge)

# # Get the gradient of the objective function at a given w and b
# def gradient( theta ):
#     w = theta[0:-1]
#     b = theta[-1]
#     hingeLoss = np.maximum( 1 - np.multiply( (X.dot( w ) + b), y ), 0 )
#     XiYi = np.multiply(X,y[:,np.newaxis])
#     hingelossXiyi = np.multiply(XiYi,hingeLoss[:,np.newaxis])
#     return  w - 2*C * np.sum( hingeLoss,axis = 0 )
  
    
# Get the CSVM gradient
def CSVMgradient( theta ):
    w = theta[0:-1]
    b = theta[-1]
    discriminant = 1 - np.multiply( (X.dot( w ) + b), y )
#     g = np.zeros( (y.size,) )
#     g[discriminant < 1] = -1
    delb = C * np.maximum(discriminant,0).dot( y ) * (-2)
    delw = w + C * (X.T * np.maximum(discriminant,0)).dot( y ) * (-2)
    return np.append( delw, delb )

    
# Get the CSVM objective value in order to plot convergence curves
def getCSVMObjVal( theta ):
    w = theta[0:-1]
    b = theta[-1]
    Loss = np.square(np.maximum( 1 - np.multiply( (X.dot( w ) + b), y ), 0 ))
    return 0.5 * w.dot( w ) + C * np.sum( Loss )


In [18]:
# Get a stochastic gradient for the CSVM objective
# Choose a random data point per iteration
def getCSVMSGrad( theta ):
    w = theta[0:-1]
    b = theta[-1]
    n = y.size
    i = random.randint( 0, n-1 )
    x = X[i,:]
    discriminant = 1 - ((x.dot( w ) + b) * y[i])
#     g = 0
#     if discriminant < 1:
#         g = -1
    delb = C * y[i] * (-2) * np.maximum(descriminant,0)
    delw = w + C * n * (x * np.maximum(descriminant,0)) * y[i] * (-2)
    return np.append( delw, delb )


array([[ 0.187531,  0.      ,  0.019502, ...,  0.023928,  0.      ,
         0.016832],
       [ 0.668091,  0.      , -0.027339, ...,  0.071717,  1.      ,
        -0.081661],
       [ 0.525146,  0.      , -0.093567, ..., -0.376834,  0.      ,
        -0.050117],
       ...,
       [ 0.385101,  0.      ,  0.134089, ..., -0.147898,  0.      ,
         0.050913],
       [ 0.163391,  0.      , -0.01197 , ...,  0.123978,  0.      ,
        -0.056383],
       [ 0.244385,  0.      , -0.127514, ...,  0.01782 ,  0.      ,
         0.3061  ]])

In [22]:
# Get a mini-batch stochastic gradient for CSVM
# Choose a random set of B samples per iteration
def getCSVMMBGrad( theta ):
    w = theta[0:-1]
    b = theta[-1]
    n = y.size
    if B <= n:
        samples = random.sample( range(0, n), B )
        X_ = X[samples,:]
        y_ = y[samples]
    else:
        X_ = X
        y_ = y
    discriminant = 1 - np.multiply( (X_.dot( w ) + b), y_ )
#     g = np.zeros( (B,) )
#     g[discriminant < 1] = -1
    delb = C * np.maximum(descriminant,0).dot( y_ ) * (-2)
    delw = w + C * n/B * (X_.T * np.maximum(descriminant,0)).dot( y_ )* (-2)
    return np.append( delw, delb )


array([136,  46,   5])

array([1, 2, 0, 0, 2, 0])