In [1]:
import numpy as np
from sklearn.svm import LinearSVC

In [2]:
Z = np.loadtxt('data')

In [3]:
y = Z[:,0]
X = Z[:,1:]


In [4]:
clf = LinearSVC(C=1.0,penalty = 'l2',loss = 'squared_hinge')

In [5]:
clf.fit(X,y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [6]:
clf.coef_

array([[-0.85750816,  0.18193707, -0.09611584,  0.48275299,  0.6245179 ,
         0.26263487, -3.4704792 ,  0.46412369,  0.21976321,  1.32746244,
        -1.28331874, -0.08017185,  0.47010648,  0.36362189, -0.14581037,
         1.02288144,  0.43255613,  0.14804773,  0.20491347, -0.31671162]])

In [7]:
clf.intercept_

array([-0.98956225])

In [8]:
final = np.matmul(X,clf.coef_.T)+clf.intercept_

In [9]:
y.shape

(20000,)

In [10]:
final.shape

(20000, 1)

In [11]:
y.reshape(20000,1)

array([[-1.],
       [-1.],
       [-1.],
       ...,
       [-1.],
       [-1.],
       [-1.]])

In [12]:
for i in range(y.shape[0]):
    final[i] = y[i] * final[i]
    

In [13]:
print(final)

[[0.70173404]
 [1.65626207]
 [1.43315978]
 ...
 [2.15354646]
 [1.25280661]
 [0.85208494]]


In [14]:
final = 1-final

In [15]:
print(final)

[[ 0.29826596]
 [-0.65626207]
 [-0.43315978]
 ...
 [-1.15354646]
 [-0.25280661]
 [ 0.14791506]]


In [16]:
for i in range(final.shape[0]):
    if(final[i] <= 0):
        final[i] = 0
    

In [17]:
for i in range(final.shape[0]):
    final[i] = final[i] * final[i]

In [18]:
np.sum(final)+0.5*np.matmul(clf.coef_,clf.coef_.T)

array([[5223.48424121]])